project_id = "fjsxwsksiitggorzsxcb"

[functions.generate-quiz]
verify_jwt = true

[functions.check-quiz-answers]
verify_jwt = true

[functions.predict-performance]
verify_jwt = false

[functions.generate-student-insights]
verify_jwt = false
